[project]
name = "project"
version = "0.1.0"
requires-python = ">=3.10"
readme = "README.md"
dependencies = [
    "cosmos-predict2[cu126]",
]

[[tool.uv.index]]
name = "cosmos-cu126"
url = "https://nvidia-cosmos.github.io/cosmos-dependencies/cu126_torch260/simple"
